// GENERATED by scripts/prepare-assets.ts — do not edit by hand.
// Run `npx tsx scripts/prepare-assets.ts` after changing anything in design/photos/.

export type Photo = {
  src: string;
  w: number;
  h: number;
  thumb: string;
  tw: number;
  th: number;
  alt: string;
};

export const photos = {
  "hero": {
    "src": "/design/photos/hero.webp",
    "w": 1200,
    "h": 1500,
    "thumb": "/design/photos/hero-t.webp",
    "tw": 640,
    "th": 800,
    "alt": "شقایق و رامین در مراسم بله‌برون"
  },
  "heroColour": {
    "src": "/design/photos/heroColour.webp",
    "w": 880,
    "h": 1100,
    "thumb": "/design/photos/heroColour-t.webp",
    "tw": 560,
    "th": 700,
    "alt": "شقایق و رامین در مراسم بله‌برون"
  },
  "og": {
    "src": "/design/photos/og.jpg",
    "w": 1200,
    "h": 630,
    "thumb": "/design/photos/og-t.jpg",
    "tw": 600,
    "th": 315,
    "alt": "شقایق و رامین"
  },
  "proposal": {
    "src": "/design/photos/proposal.webp",
    "w": 823,
    "h": 1100,
    "thumb": "/design/photos/proposal-t.webp",
    "tw": 523,
    "th": 700,
    "alt": "دسته‌گل خواستگاری"
  },
  "proposalSquare": {
    "src": "/design/photos/proposalSquare.webp",
    "w": 700,
    "h": 700,
    "thumb": "/design/photos/proposalSquare-t.webp",
    "tw": 560,
    "th": 560,
    "alt": "خواستگاری"
  },
  "ringMoment": {
    "src": "/design/photos/ringMoment.webp",
    "w": 1120,
    "h": 1400,
    "thumb": "/design/photos/ringMoment-t.webp",
    "tw": 608,
    "th": 760,
    "alt": "لحظه‌ی دست کردن حلقه"
  },
  "venue": {
    "src": "/design/photos/venue.webp",
    "w": 1600,
    "h": 1200,
    "thumb": "/design/photos/venue-t.webp",
    "tw": 820,
    "th": 615,
    "alt": "چیدمان سفره‌ی بله‌برون"
  },
  "ringBouquet": {
    "src": "/design/photos/ringBouquet.webp",
    "w": 1500,
    "h": 1125,
    "thumb": "/design/photos/ringBouquet-t.webp",
    "tw": 800,
    "th": 600,
    "alt": "حلقه روی دسته‌گل سفید و آبی"
  },
  "sofreh": {
    "src": "/design/photos/sofreh.webp",
    "w": 975,
    "h": 1300,
    "thumb": "/design/photos/sofreh-t.webp",
    "tw": 540,
    "th": 720,
    "alt": "جزئیات سفره‌ی عقد"
  },
  "ringDetail": {
    "src": "/design/photos/ringDetail.webp",
    "w": 1500,
    "h": 1125,
    "thumb": "/design/photos/ringDetail-t.webp",
    "tw": 800,
    "th": 600,
    "alt": "حلقه‌ی نامزدی"
  },
  "candlelit": {
    "src": "/design/photos/candlelit.webp",
    "w": 240,
    "h": 320,
    "thumb": "/design/photos/candlelit-t.webp",
    "tw": 240,
    "th": 320,
    "alt": "لحظه‌ای در نور شمع"
  },
  "tableau": {
    "src": "/design/photos/tableau.webp",
    "w": 600,
    "h": 800,
    "thumb": "/design/photos/tableau-t.webp",
    "tw": 450,
    "th": 600,
    "alt": "نمای کامل سفره"
  }
} as const satisfies Record<string, Photo>;

export type PhotoId = keyof typeof photos;
