// GENERATED by scripts/prepare-assets.ts — do not edit by hand.
// Run `npx tsx scripts/prepare-assets.ts` after changing anything in design/photos/.

export type Photo = {
  src: string;
  w: number;
  h: number;
  thumb: string;
  tw: number;
  th: number;
  alt: string;
};

export const photos = {
  "hero": {
    "src": "/design/photos/hero.webp",
    "w": 990,
    "h": 1400,
    "thumb": "/design/photos/hero-t.webp",
    "tw": 538,
    "th": 760,
    "alt": "شقایق و رامین در مراسم بله‌برون"
  },
  "baleBoron": {
    "src": "/design/photos/baleBoron.webp",
    "w": 707,
    "h": 1000,
    "thumb": "/design/photos/baleBoron-t.webp",
    "tw": 453,
    "th": 640,
    "alt": "شقایق و رامین در شب بله‌برون"
  },
  "proposal": {
    "src": "/design/photos/proposal.webp",
    "w": 748,
    "h": 1000,
    "thumb": "/design/photos/proposal-t.webp",
    "tw": 479,
    "th": 640,
    "alt": "شقایق و رامین در شب خواستگاری"
  },
  "og": {
    "src": "/design/photos/og.jpg",
    "w": 1200,
    "h": 630,
    "thumb": "/design/photos/og-t.jpg",
    "tw": 600,
    "th": 315,
    "alt": "شقایق و رامین"
  },
  "gallery1": {
    "src": "/design/photos/gallery1.webp",
    "w": 600,
    "h": 800,
    "thumb": "/design/photos/gallery1-t.webp",
    "tw": 465,
    "th": 620,
    "alt": "قابی از شب بله‌برون"
  },
  "gallery2": {
    "src": "/design/photos/gallery2.webp",
    "w": 800,
    "h": 633,
    "thumb": "/design/photos/gallery2-t.webp",
    "tw": 620,
    "th": 491,
    "alt": "قابی از شب بله‌برون"
  },
  "gallery3": {
    "src": "/design/photos/gallery3.webp",
    "w": 785,
    "h": 800,
    "thumb": "/design/photos/gallery3-t.webp",
    "tw": 608,
    "th": 620,
    "alt": "قابی از شب بله‌برون"
  },
  "gallery4": {
    "src": "/design/photos/gallery4.webp",
    "w": 600,
    "h": 800,
    "thumb": "/design/photos/gallery4-t.webp",
    "tw": 465,
    "th": 620,
    "alt": "قابی از شب بله‌برون"
  },
  "gallery5": {
    "src": "/design/photos/gallery5.webp",
    "w": 800,
    "h": 600,
    "thumb": "/design/photos/gallery5-t.webp",
    "tw": 620,
    "th": 465,
    "alt": "قابی از شب بله‌برون"
  },
  "gallery6": {
    "src": "/design/photos/gallery6.webp",
    "w": 825,
    "h": 1100,
    "thumb": "/design/photos/gallery6-t.webp",
    "tw": 465,
    "th": 620,
    "alt": "خونچه"
  }
} as const satisfies Record<string, Photo>;

export type PhotoId = keyof typeof photos;
